services:
  nextcloud_db:
    image: mariadb
    restart: unless-stopped
    container_name: nextcloud_db
    volumes:
      - /home/david/nextcloud-project/mariadb-data:/var/lib/mysql

  nextcloud_web:
    build: ./apache
    restart: unless-stopped
    container_name: nexcloud_web
    volumes:
        - ./apache/config/security.conf:/etc/apache2/conf-available/security.conf:ro
        - ./apache/config/modsecurity-custom.conf:/etc/apache2/mods-available/security2.conf:ro

  nextcloud:
    image: nextcloud
    restart: unless-stopped
    container_name: nextcloud
    volumes:
      - /home/david/nextcloud-project/nextcloud:/var/www/html
      - /media/ext-storage/nextcloud-data:/var/www/html/data
