# Start in DetectionOnly to test for false positives. 
# Change to "On" once you are sure Nextcloud functions normally.
SecRuleEngine DetectionOnly

SecRequestBodyAccess On
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml

# Default logging location
SecAuditEngine RelevantOnly
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/apache2/modsec_audit.log
